### PR TITLE
replacing array_push with faster []

### PR DESCRIPTION
**Pull request by pine3ree**

### CODE REVIEW

**Comment by ozh** [comment]
This notation requires 5.4+

**Comment by philo23** [comment]
I don't think so, this syntax has been in PHP for a long time.

You might be thinking of the new array syntax that replaces using `array()`

**Comment by pine3ree** [comment]
it's a simple standard array element assignment. It has nothing to do with php 5.4 or new array notation. [] array operator is as twice as fast as array_push.

**Comment by ozh** [comment]
My bad, [indeed](http://3v4l.org/nfGCE).

**Comment by pine3ree** [comment]
@ozh 

no problem. :-)

**Pull request merged**
