### PR TITLE
JSONP support

### PR DESCRIPTION
**Pull request by ozh**
Hi

Thanks a zillion for this neat little framework. I'm using it to develop api.yourls.org, it's lovely and has everything needed to roll out APIs :-)

I would like it to support JSONP out of the box, would you be interested in a pull request?

My implementation works this way:
- new default setting to set the callback name: `flight.jsonp.callback`
- new function `_jsonp()` outputting JSON padded with the callback value (eg `/route/?jsonp=foo` will output `foo(...JSON response here...);`

Thanks for your time!

### CODE REVIEW

**Comment by ozh** [comment]
thanks!

**Comment by ozh** [comment]
The doc needs updating now, in http://flightphp.com/learn#configuration and http://flightphp.com/learn#methods

**Comment by kamov** [comment]
Thanks!

An example of usage will be useful.

Thanks!

**Comment by ozh** [comment]
It works the same as the `json` method. Something like:

``` php
// Set the JSONP callback parameter to "callback" (default: "jsonp")
Flight::set( 'flight.jsonp.callback', 'callback' );

Flight::route('/myroute', function(){
    $data = function_to_get_some_data();
    Flight::jsonp( $data );
});
```

And then request url `server.com/myroute?callback=my_function` to get a JSONP response

A more practical example would be to check for the callback parameter and deciding whether to output json on jsonp. Full example:

``` php
<?php
require 'flight/Flight.php';

// Set the JSONP callback parameter to "callback" (default: "jsonp")
$callback = 'callback';
Flight::set( 'flight.jsonp.callback', $callback );

Flight::route('/myroute', function(){
    $data = function_to_get_some_data();
    if( Flight::request()->query[ $callback ] ) {
        Flight::jsonp( $data );
    } else {
        Flight::json( $data );
    }
});

Flight::start();
?>
```

**Comment by kamov** [comment]
@ozh thanks! This help!

**Pull request merged**
